version: "3.4"

services:
    db:
      image: postgres:15.2-alpine
      restart: unless-stopped
      networks:
        - fake-local-network
      env_file:
          - ./.env
      environment:
          - PGDATA=/var/lib/postgresql/data/pgdata
      volumes:
          - ./volumes/db:/var/lib/postgresql/data/pgdata
      ports:
          - "5432:5432"

    backend:
      build: 
        context: ./backend
        dockerfile: Dockerfile.dev
      restart: unless-stopped
      networks:
        - fake-local-network
        # - kafka-network
      env_file:
        - ./backend/docker.env
      volumes:
        - ./backend:/usr/src/app
      ports:
        - "8000:8000"
      depends_on:
        - db

    frontend:
      build: ./frontend
      restart: unless-stopped
      env_file:
        - ./frontend/docker.env
      ports:
        - "3000:3000"
      volumes:
        - ./frontend:/usr/src/app
      depends_on:
        - backend

    robot:
      build:
        context: ./python-server
        dockerfile: Dockerfile
      ports:
        - 8150:8150
      volumes:
        - ./python-server:/app
      networks:
        - fake-local-network

    mosquitto:
      image: eclipse-mosquitto:2.0
      restart: unless-stopped
      ports:
        - "1883:1883"
        - "9001:9001"
      networks:
        - fake-local-network
      volumes:
        - ./mosquitto/config:/mosquitto/config
        - ./mosquitto/data:/mosquitto/data
        - ./mosquitto/log:/mosquitto/log

networks:
  fake-local-network:
    driver: bridge
    ipam:
      config:
        - subnet: "172.29.0.0/16"


    